### ISSUE TITLE
the problem of running the r-process example

### ISSUE THREAD

**Issue by sameulleaf** [nuc-astro/WinNet#6]

**Comment by Mreichert91** [comment]
Can you elaborate a bit more on the problem? Which example exactly does not work and what does it do?

**Comment by sameulleaf** [comment]
Sorry for the delayed reply. I am a very rookie in nuclear astrophysics. I am trying to run the r-process examples with updated mass excess and keep the other data fixed for sensitivity study. Note that the differences between our mass data and FRDM mass data can over 5 MeV in neutron-rich regions, after successfully replacing mass data and running the Example_NSM_dyn_ejecta_rosswog, the returned abundance is almost the same as those with FRDM mass data. I also tried several examples, but the results still didn't change.  Would you please tell me the reasons and how to fix it?

Many thanks for your kindness.

**Comment by Mreichert91** [comment]
Hi,

If I understand you correctly you were only replacing the mass excess (in the winvn file, parameter _isotopes\_file_). 
In your example, this mass excess is only used to calculate the initial abundances using nuclear statistical equilibrium (and it may have a minor impact on your temperature evolution). Therefore, the impact that you see will also only be minor. WinNet is not able to recalculate (forward) reaction rates out of the masses and the reaction rates that WinNet is using are usually stored in the Reaclib file (parameter _reaclib\_file_).
For a sensitivity study, there is a step in between as you would need to derive not only masses, but also reaction rates with a reaction code such as Talys (https://github.com/arjankoning1/talys). Talys is giving you the reactions in a tabulated form and you would have to input them into WinNet via the parameters  _tabulated\_rates\_file_ and  _use\_tabulated\_rates_ (see Example\_AGB\_nishimura for an example of a parameter file). Examplary publications were WinNet was used in such a way are [Martin et al. 2016](https://ui.adsabs.harvard.edu/abs/2016PhRvL.116l1101M/abstract), [Bliss et al. 2020](https://ui.adsabs.harvard.edu/abs/2020PhRvC.101e5807B/abstract), [Psaltis et al. 2022](https://ui.adsabs.harvard.edu/abs/2022ApJ...935...27P/abstract), [Reichert et al. 2024](https://ui.adsabs.harvard.edu/abs/2024MNRAS.529.3197R/abstract). 

While WinNet is not able to calculate forward rates, you could still get a first rough estimate for testing purposes by recalculating only the inverse reactions out of your masses. For this you could set  _use\_detailed\_balance=yes_ and  _use\_detailed\_balance\_q\_reac=no_ . Be aware that this will replace and recalculate all inverse reactions that are contained in the reaclib (and flagged with a "v" there). Calculating only inverse reactions and not recalculating the forward ones will make your rates generally inconsistent (since forward and inverse rates will be based on different masses) but to see only a first rough impression of the differences it may be enough. I would expect that the nucleosynthetic path should actually be the same when you are in (n,gamma)(gamma,n) equilibrium by only changing the inverse rates compared to changing forward and inverse rates, however when you drop out of this equilibrium you will get deviations.

Let me know if this helped.

**Comment by sameulleaf** [comment]
Thanks for your detailed explanation, I appreciate it. I have several questions for your reply.
First,  following your suggestions, I saw the sentences use_detailed_balance=yes and use_detailed_balance_q_reac=no in Example_AGB_nishimura.par in par folder,  but I checked several examples such as Example_NSM_wind_martin.par,  these two commands are not found. Could I just copy these two commands to other example.par files for recalculating reverse reaction rates?
Second,  besides recalculating forward reaction rates with the talys,  beta decay half-life is also an important input in r-process simulations, should I consider it or leave it alone for a  mass sensitivity study?
 
Thanks again for your kindness,
Best regards.

**Comment by Mreichert91** [comment]
Hi,

Yes, you could copy these two commands into another parameter file and the reverse reaction rates are recalculated by WinNet using the masses that you gave in the winvn file.

Regarding the $\beta$-decay half-lifes I can not really give any advice and I guess that you have to decide this yourself. If you want to change them you could do this with the parameters [_use\_beta\_decay\_file_](https://nuc-astro.github.io/WinNet/parameters.html#use_beta_decay_file), [_beta\_decay\_file_](https://nuc-astro.github.io/WinNet/parameters.html#beta_decay_file) , and [_beta\_decay\_src\_ignore_](https://nuc-astro.github.io/WinNet/parameters.html#beta_decay_src_ignore) as in the _Example\_NSM\_dyn\_ejecta\_rosswog\_beta.par_ example.

**Comment by sameulleaf** [comment]
Thanks for your suggestions.
